# Generated by Django 5.2.7 on 2025-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_zip', models.FileField(blank=True, null=True, upload_to='zips/')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
